const ACCESS_TOKEN_EXPIRY_TIME = "5m";
const REFRESH_TOKEN_EXPIRY_TIME = "1d";
const EMAIL_VERIFICATION_TOKEN_EXPIRY_TIME = "1d";

module.exports = {
  ACCESS_TOKEN_EXPIRY_TIME,
  REFRESH_TOKEN_EXPIRY_TIME,
  EMAIL_VERIFICATION_TOKEN_EXPIRY_TIME,
};
